import type { Metadata } from "next";
import { Preahvihear } from "next/font/google";
import "../styles/globals.scss";

const preahvihear = Preahvihear({
  weight: "400", // Specify the desired weights if available (Preahvihear often has only one weight)
  subsets: ["latin"], // Include necessary subsets
  display: "swap", // Recommended for better performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${preahvihear}`}>{children}</body>
    </html>
  );
}
